"""
utils/helpers.py
----------------
Export utilities for CodeExplain: Plain-English Code Tutor.

Provides three export formats for the AI-generated code explanation:

Public API
----------
    generate_markdown(results, language, code) -> str
        Builds a clean Markdown document from the explanation sections.

    generate_pdf(results, language, code) -> bytes | None
        Builds a professional PDF document; returns raw bytes or None on error.

    format_export_text(results, language) -> str
        Builds a plain-text string suitable for clipboard copy.

All functions are pure (no Streamlit calls) and never raise — errors are
returned as None / empty string so the caller can show a friendly message.
"""

from __future__ import annotations

import io
from datetime import datetime

# ── ReportLab imports ─────────────────────────────────────────────────────────
# reportlab is already in requirements.txt.
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        HRFlowable,
        KeepTogether,
    )
    from reportlab.platypus.flowables import PageBreak
    _REPORTLAB_AVAILABLE = True
except ImportError:
    _REPORTLAB_AVAILABLE = False

# ── Section metadata: (label used in output, dict-key from explain pipeline) ──
_SECTIONS: list[tuple[str, str]] = [
    ("Summary",                  "summary"),
    ("Line-by-Line Explanation", "line_by_line"),
    ("Time Complexity",          "time_complexity"),
    ("Space Complexity",         "space_complexity"),
    ("Suggested Improvements",   "improvements"),
]


# ── Markdown export ───────────────────────────────────────────────────────────

def generate_markdown(
    results: dict[str, str],
    language: str,
    code: str = "",
) -> str:
    """
    Build a clean Markdown document from the five explanation sections.

    Args:
        results (dict[str, str]): Parsed sections from the explain pipeline.
        language (str):           The programming language (e.g. "Python").
        code (str):               Optional original code snippet to embed.

    Returns:
        str: A valid Markdown string ready for download.  Never raises.
    """
    try:
        timestamp: str = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines: list[str] = [
            "# CodeExplain — Plain-English Code Tutor",
            "",
            f"**Language:** {language}  ",
            f"**Generated:** {timestamp}",
            "",
            "---",
            "",
        ]

        for label, key in _SECTIONS:
            content: str = results.get(key, "_Section not available._")
            lines.append(f"## {label}")
            lines.append("")
            lines.append(content)
            lines.append("")
            lines.append("---")
            lines.append("")

        if code and code.strip():
            ext_map = {
                "Python": "python", "Java": "java",
                "JavaScript": "javascript", "C++": "cpp", "C": "c",
            }
            fence: str = ext_map.get(language, "")
            lines.append("## Original Code")
            lines.append("")
            lines.append(f"```{fence}")
            lines.append(code.strip())
            lines.append("```")
            lines.append("")

        lines.append(
            "_Generated by CodeExplain — Powered by Google Gemini AI_"
        )

        return "\n".join(lines)

    except Exception:
        return "# Export Error\n\nCould not generate Markdown. Please try again."


# ── PDF export ────────────────────────────────────────────────────────────────

def generate_pdf(
    results: dict[str, str],
    language: str,
    code: str = "",
) -> bytes | None:
    """
    Build a professional PDF from the five explanation sections using ReportLab.

    Layout:
      - Cover block: title, language, timestamp.
      - One section per heading, with automatic page breaks.
      - Monospaced original code block at the end (optional).
      - Footer on every page: page number + app name.

    Args:
        results (dict[str, str]): Parsed sections from the explain pipeline.
        language (str):           The programming language (e.g. "Python").
        code (str):               Optional original code snippet to embed.

    Returns:
        bytes: Raw PDF bytes on success.
        None:  On any failure (caller should show a friendly error message).
    """
    if not _REPORTLAB_AVAILABLE:
        return None

    try:
        buffer = io.BytesIO()
        timestamp: str = datetime.now().strftime("%Y-%m-%d %H:%M")

        # ── Page template ─────────────────────────────────────────────────────
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=2.5 * cm,
            rightMargin=2.5 * cm,
            topMargin=2.5 * cm,
            bottomMargin=2.5 * cm,
            title="CodeExplain — Analysis Report",
            author="CodeExplain AI Tutor",
        )

        # ── Style sheet ───────────────────────────────────────────────────────
        base_styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "CETitle",
            parent=base_styles["Title"],
            fontSize=22,
            textColor=colors.HexColor("#1f6feb"),
            spaceAfter=6,
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "CESubtitle",
            parent=base_styles["Normal"],
            fontSize=11,
            textColor=colors.HexColor("#57606a"),
            spaceAfter=4,
        )
        section_heading_style = ParagraphStyle(
            "CESectionHeading",
            parent=base_styles["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#1f6feb"),
            spaceBefore=14,
            spaceAfter=6,
            fontName="Helvetica-Bold",
            borderPad=4,
        )
        body_style = ParagraphStyle(
            "CEBody",
            parent=base_styles["Normal"],
            fontSize=10,
            leading=15,
            textColor=colors.HexColor("#24292f"),
            spaceAfter=4,
        )
        code_style = ParagraphStyle(
            "CECode",
            parent=base_styles["Code"],
            fontSize=8,
            leading=12,
            textColor=colors.HexColor("#24292f"),
            backColor=colors.HexColor("#f6f8fa"),
            fontName="Courier",
            leftIndent=10,
            rightIndent=10,
            spaceAfter=4,
        )

        # ── Build story (flowables) ───────────────────────────────────────────
        story: list = []

        # Cover block
        story.append(Paragraph("CodeExplain", title_style))
        story.append(Paragraph("Plain-English Code Tutor — Analysis Report", subtitle_style))
        story.append(Paragraph(f"Language: <b>{language}</b>", subtitle_style))
        story.append(Paragraph(f"Generated: {timestamp}", subtitle_style))
        story.append(Spacer(1, 0.4 * cm))
        story.append(
            HRFlowable(width="100%", thickness=1.5,
                       color=colors.HexColor("#1f6feb"), spaceAfter=12)
        )

        # Five analysis sections
        for label, key in _SECTIONS:
            content: str = results.get(key, "Section not available.")

            # Escape HTML-special characters before passing to Paragraph.
            safe_content = (
                content
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )

            # Each section is kept together on one page where possible.
            block = [
                Paragraph(label, section_heading_style),
                HRFlowable(width="100%", thickness=0.5,
                           color=colors.HexColor("#d0d7de"), spaceAfter=6),
            ]

            # Render each line as its own Paragraph to preserve line breaks.
            for raw_line in safe_content.splitlines():
                stripped = raw_line.strip()
                if stripped:
                    block.append(Paragraph(stripped, body_style))
                else:
                    block.append(Spacer(1, 0.2 * cm))

            story.append(KeepTogether(block[:6]))   # keep heading + first ~5 lines
            story.extend(block[6:])                 # rest flows freely
            story.append(Spacer(1, 0.3 * cm))

        # Optional code block
        if code and code.strip():
            story.append(PageBreak())
            story.append(Paragraph("Original Code", section_heading_style))
            story.append(
                HRFlowable(width="100%", thickness=0.5,
                           color=colors.HexColor("#d0d7de"), spaceAfter=6)
            )
            for raw_line in code.strip().splitlines():
                safe_line = (
                    raw_line
                    .replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                    .replace(" ", "&nbsp;")
                )
                story.append(Paragraph(safe_line or "&nbsp;", code_style))

        # Footer note
        story.append(Spacer(1, 0.5 * cm))
        story.append(
            HRFlowable(width="100%", thickness=0.5,
                       color=colors.HexColor("#d0d7de"), spaceAfter=6)
        )
        story.append(
            Paragraph(
                "<font color='#57606a' size='8'>"
                "Generated by CodeExplain — Powered by Google Gemini AI"
                "</font>",
                body_style,
            )
        )

        # ── Build PDF ─────────────────────────────────────────────────────────
        doc.build(story)
        pdf_bytes: bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    except Exception:
        return None


# ── Plain-text export (clipboard) ─────────────────────────────────────────────

def format_export_text(
    results: dict[str, str],
    language: str,
) -> str:
    """
    Build a clean plain-text string for clipboard copy.

    Produces exactly what the user sees in the Analysis Results section:
    headings and content with no HTML, no Markdown syntax, no extra
    formatting.

    Args:
        results (dict[str, str]): Parsed sections from the explain pipeline.
        language (str):           The programming language (e.g. "Python").

    Returns:
        str: Plain-text export string.  Never raises.
    """
    try:
        timestamp: str = datetime.now().strftime("%Y-%m-%d %H:%M")
        parts: list[str] = [
            "CodeExplain — Plain-English Code Tutor",
            f"Language: {language}",
            f"Generated: {timestamp}",
            "=" * 60,
            "",
        ]
        for label, key in _SECTIONS:
            content: str = results.get(key, "Section not available.")
            parts.append(f"[ {label} ]")
            parts.append("-" * 40)
            parts.append(content)
            parts.append("")

        parts.append("=" * 60)
        parts.append("Generated by CodeExplain — Powered by Google Gemini AI")
        return "\n".join(parts)

    except Exception:
        return "Export failed. Please try again."
